# Generated by Django 2.0 on 2017-12-26 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=256)),
                ('type', models.CharField(choices=[('tt', 'Twitter'), ('fb', 'Facebook'), ('em', 'Email'), ('wc', 'WeChat'), ('ma', 'Mailing'), ('gh', 'Github'), ('cp', 'Codepen'), ('lk', 'Linkedin'), ('cp', 'Cellphone'), ('ot', 'Other')], max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greeting', models.CharField(max_length=256)),
                ('about', models.TextField(max_length=1024)),
                ('contact_one', models.IntegerField(blank=True)),
                ('contact_two', models.IntegerField(blank=True)),
                ('contact_three', models.IntegerField(blank=True)),
                ('contact_four', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='QandA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=256)),
                ('answer', models.TextField(max_length=1024)),
                ('display', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_page.MyProfile')),
            ],
        ),
    ]
