# Generated by Django 2.0 on 2017-12-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmethod',
            old_name='type',
            new_name='contact_type',
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='contact_four',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='contact_one',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='contact_three',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='contact_two',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
