# Generated by Django 2.0 on 2017-12-26 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0003_auto_20171226_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myprofile',
            name='contact_four',
        ),
        migrations.RemoveField(
            model_name='myprofile',
            name='contact_one',
        ),
        migrations.RemoveField(
            model_name='myprofile',
            name='contact_three',
        ),
        migrations.RemoveField(
            model_name='myprofile',
            name='contact_two',
        ),
        migrations.AddField(
            model_name='contactmethod',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home_page.MyProfile'),
        ),
    ]
