# Generated by Django 2.0 on 2017-12-26 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0004_auto_20171226_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='display_order',
            field=models.IntegerField(default=0, unique=False),
        ),
    ]
