# Generated by Django 2.0 on 2017-12-26 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0006_auto_20171226_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='display_order',
            field=models.IntegerField(),
        ),
    ]
